### ISSUE TITLE
Time to release the code

### ISSUE THREAD

**Issue by sunhan1997** [HRI-EU/flow-matching-policy#1]
Hello, thank you for your interesting work. When do you plan to release the code? I am looking forward to learning about your work on flow matching policy.

**Comment by fan6zh** [comment]
https://github.com/HRI-EU/flow_matching

It will be here these two days

**Comment by sunhan1997** [comment]
Thank you very much! I am looking forward to it!




| |
孙晗
|
|
***@***.***
|
---- Replied Message ----
| From | Fan ***@***.***> |
| Date | 12/20/2024 19:05 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [HRI-EU/flow-matching-policy] Time to release the code (Issue #1) |

https://github.com/HRI-EU/flow_matching

It will be here these two days
